services:
  postgres:
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 1s
      timeout: 1s
      retries: 200
  
  postgres-migrate:
    entrypoint: []
    command: ["/bin/sh", "-c", "flyway migrate; echo 'flyway ready'; while true; do sleep 3600; done"]
    stdin_open: true
    tty: true
  
  dataset-loader:
    entrypoint: []
    # command: ["/bin/sh", "-c", "echo 'dataset-loader ready'; while true; do sleep 3600; done"]
    # command: ["/bin/sh", "-c", "echo 'dataset-loader ready'; pwd"]
    command: ["python", "./index.py"]
    volumes:
      - ./dataset-loader:/app/dataset-loader
    stdin_open: true
    tty: true
    depends_on:
      postgres-migrate:
        condition: service_started

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ./server:/app
    stdin_open: true
    tty: true

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: dev
      # target: runtime
    volumes:
      - ./client:/app
    ports:
      - "3000:3000"
    # command: ["pnpm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "3000"]
    stdin_open: true
    tty: true

  caddy:
    environment:
      - SITE_ADDR="http://localhost:3111"
      - CADDY_GLOBAL_OPTIONS=auto_https off
    ports:
      - "3111:3111"
